name: down4
description: Down4

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-0.0.dev"
#  sdk: ">=2.19.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Packages
  qr: ^3.0.1
  video_thumbnail: ^0.5.3
  mobile_scanner: ^2.0.0
  path_provider: ^2.0.9
  base85: ^1.0.3
  flutter_video_info: ^1.3.1
  http: ^0.13.4
  file_picker: ^5.2.2
  english_words: ^4.0.0
  better_player: ^0.0.69
  video_compress: ^3.1.2
  mime: ^1.0.4
  cbl: ^2.1.8
  camera: ^0.10.0+4
  firebase_core: ^2.1.0
  flutter_image_compress: ^1.1.0
  firebase_messaging: ^14.0.2
  firebase_storage: ^11.0.2
  firebase_auth: ^4.0.1
  flutter_local_notifications: ^12.0.3
  firebase_core_platform_interface: ^4.5.1
  pointycastle: ^3.6.0
  bs58: ^1.0.2
  firebase_database: ^10.0.2
  cloud_firestore: ^4.0.2
  cbl_flutter: ^2.0.6
  cbl_flutter_ce: ^2.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/down4_inverted.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_launcher_icons: ^0.11.0


  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/texts/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Merriweather
      fonts:
      - asset: assets/fonts/Merriweather-Regular.ttf
    - family: Alegreya
      fonts:
      - asset: assets/fonts/Alegreya-Regular.ttf
    - family: Alice
      fonts:
      - asset: assets/fonts/Alice-Regular.ttf
    - family: EBGaramond
      fonts:
      - asset: assets/fonts/EBGaramond-Regular.ttf
    - family: Handlee
      fonts:
      - asset: assets/fonts/Handlee-Regular.ttf
    - family: LobsterTwo
      fonts:
      - asset: assets/fonts/LobsterTwo-Regular.ttf
    - family: SourceCodePro
      fonts:
      - asset: assets/fonts/SourceCodePro-Regular.ttf
    - family: NotoSerif
      fonts:
      - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: Tapestry
      fonts:
      - asset: assets/fonts/Tapestry-Regular.ttf
    - family: MonteCarlo
      fonts:
      - asset: assets/fonts/MonteCarlo-Regular.ttf
    - family: Sacramento
      fonts:
      - asset: assets/fonts/Sacramento-Regular.ttf
    - family: Kaushan
      fonts:
      - asset: assets/fonts/KaushanScript-Regular.ttf
    - family: Kalam
      fonts:
      - asset: assets/fonts/Kalam-Regular.ttf
    - family: Ubuntu
      fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Updock
      fonts:
      - asset: assets/fonts/Updock-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
