// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDszPbS34G6AAcID17BiHCvRZSSEvqdCUM',
    appId: '1:141478909490:web:72fcce45be4be0d0708e2b',
    messagingSenderId: '141478909490',
    projectId: 'down4-26ee1',
    authDomain: 'down4-26ee1.firebaseapp.com',
    databaseURL: 'https://down4-26ee1-default-rtdb.firebaseio.com',
    storageBucket: 'down4-26ee1.appspot.com',
    measurementId: 'G-T4JF2BFN0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcwaJCbAb8VxzUPRMJiB5FWtASm-39d4',
    appId: '1:141478909490:android:6bc20f0eb0b1daa4708e2b',
    messagingSenderId: '141478909490',
    projectId: 'down4-26ee1',
    databaseURL: 'https://down4-26ee1-default-rtdb.firebaseio.com',
    storageBucket: 'down4-26ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa-DOYin0sy5WvcAXjdx5USYqV-NPMEmo',
    appId: '1:141478909490:ios:9d73b82b3f619550708e2b',
    messagingSenderId: '141478909490',
    projectId: 'down4-26ee1',
    databaseURL: 'https://down4-26ee1-default-rtdb.firebaseio.com',
    storageBucket: 'down4-26ee1.appspot.com',
    iosClientId: '141478909490-a0vb5iscin8uk97h19td7dh9kbv7of1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestproject',
  );
}
